### ISSUE TITLE
Builds are no longer available

### ISSUE THREAD

**Issue by jonwolski** [landro/jtcl-irule#4]
JFrog no longer makes the build available bintray. Any chance you could make the jar available through GitHub releases or something like https://mvnrepository.com/repos/central?

Building from source is particularly difficult since it requires building the JTCL source, and _that_ requires Sun jdk 1.6.

**Comment by olanystrom** [comment]
Any updates on this?
I keep an old copy of jtcl-irule-0.9.jar offline for now.

**Comment by landro** [comment]
Thanks for reaching out @olanystrom. Will look into this in due course.

**Comment by landro** [comment]
I just uploaded jtcl-irule-0.9.jar to the 0.9 release: https://github.com/landro/jtcl-irule/releases/tag/v0.9
